### ISSUE TITLE
Write frames

### ISSUE THREAD

**Issue by Harsh-Vavaiya** [isarandi/poseviz#4]
@isarandi is there any way to write these poseviz output frames into video from one angle?

**Comment by isarandi** [comment]
Yes, you can do that by calling

```python
viz.new_sequence_output(output_video_path, fps=desired_output_fps)
```

You can start a new video by calling the same function again with a different path.
The function `viz.finalize_sequence_output()` can also be called if you want to flush the current video fully to disk. This is not mandatory, the video will be saved correctly also if you just exit the `with` clause of PoseViz, or when PoseViz is otherwise closed.
